config/routes.rb
Rails.application.routes.draw do
  resources :indefinitions
  get '/indef' => 'indefinitions#index'
  root to: 'indefinitions#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/indefinition.rb
class Indefinition < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/indefinitions_controller.rb
class IndefinitionsController < ApplicationController
  before_action :set_indefinition, only: [:show, :edit, :update, :destroy]

  # GET /indefinitions
  # GET /indefinitions.json
  def index
    @indefinitions = Indefinition.all
  end

  # GET /indefinitions/1
  # GET /indefinitions/1.json
  def show
  end

  # GET /indefinitions/new
  def new
    @indefinition = Indefinition.new
  end

  # GET /indefinitions/1/edit
  def edit
  end

  # POST /indefinitions
  # POST /indefinitions.json
  def create
    @indefinition = Indefinition.new(indefinition_params)

    respond_to do |format|
      if @indefinition.save
        format.html { redirect_to @indefinition, notice: 'Indefinition was successfully created.' }
        format.json { render :show, status: :created, location: @indefinition }
      else
        format.html { render :new }
        format.json { render json: @indefinition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /indefinitions/1
  # PATCH/PUT /indefinitions/1.json
  def update
    respond_to do |format|
      if @indefinition.update(indefinition_params)
        format.html { redirect_to @indefinition, notice: 'Indefinition was successfully updated.' }
        format.json { render :show, status: :ok, location: @indefinition }
      else
        format.html { render :edit }
        format.json { render json: @indefinition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /indefinitions/1
  # DELETE /indefinitions/1.json
  def destroy
    @indefinition.destroy
    respond_to do |format|
      format.html { redirect_to indefinitions_url, notice: 'Indefinition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_indefinition
      @indefinition = Indefinition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def indefinition_params
      params.require(:indefinition).permit(:nom, :description, :string)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/indefinition_helper.rb
module IndefinitionHelper
end

app/helpers/indefinitions_helper.rb
module IndefinitionsHelper
end

app/views/indefinitions/_form.html.erb
<%= form_for(indefinition) do |f| %>
  <% if indefinition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(indefinition.errors.count, "error") %> prohibited this indefinition from being saved:</h2>

      <ul>
      <% indefinition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom %>
    <%= f.text_field :nom %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/indefinitions/edit.html.erb
<h1>Editing Indefinition</h1>

<%= render 'form', indefinition: @indefinition %>

<%= link_to 'Show', @indefinition %> |
<%= link_to 'Back', indefinitions_path %>

app/views/indefinitions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Indefinitions</h1>

<table>
  <thead>
    <tr>
      <th>Nom</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= @indefinitions.length %>
    <% @indefinitions.each do |indefinition| %>
      <tr>
        <td><%= indefinition.nom %></td>
        <td><%= indefinition.description %></td>
        <td><%= link_to 'Show', indefinition %></td>
        <td><%= link_to 'Edit', edit_indefinition_path(indefinition) %></td>
        <td><%= link_to 'Destroy', indefinition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Indefinition', new_indefinition_path %>

app/views/indefinitions/new.html.erb
<h1>New Indefinition</h1>

<%= render 'form', indefinition: @indefinition %>

<%= link_to 'Back', indefinitions_path %>

app/views/indefinitions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @indefinition.nom %>
</p>

<p>
  <strong>Description:</strong>
  <%= @indefinition.description %>
</p>


<%= link_to 'Edit', edit_indefinition_path(@indefinition) %> |
<%= link_to 'Back', indefinitions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Compteur</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>